import React, { useState } from 'react';
import { Bookmark, Building2, CheckCircle2, ChevronDown, ExternalLink, MapPin } from 'lucide-react';
import { AnimatePresence, motion as Motion } from 'framer-motion';

export default function JobCard({ job, saved, onSave }) {
  const [expanded, setExpanded] = useState(false);
  const score = Math.round(job.match_score || 0);
  const scoreColor = score >= 75 ? 'bg-emerald-400' : score >= 55 ? 'bg-amber-400' : 'bg-cyan-400';
  return <Motion.article initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/85 shadow-xl shadow-black/15 transition hover:border-slate-700"><div className="h-1.5 bg-slate-800"><div className={`h-full ${scoreColor}`} style={{ width: `${score}%` }} /></div><div className="p-5 sm:p-6"><div className="flex gap-4"><div className="min-w-0 flex-1"><h3 className="text-xl font-semibold text-white">{job.title}</h3><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm text-slate-400"><span className="flex items-center gap-1.5"><Building2 className="h-4 w-4" />{job.company}</span><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" />{job.location || 'Location not listed'}</span><span>{job.employment_type || 'Full-time'}</span></div></div><div className="shrink-0 text-right"><p className="text-2xl font-bold text-white">{score}%</p><p className="text-xs uppercase tracking-wide text-slate-500">match</p></div></div>
    <div className="mt-5 rounded-xl border border-cyan-400/15 bg-cyan-400/5 p-4"><p className="text-sm leading-6 text-cyan-100"><span className="font-semibold text-cyan-300">Why this suits you: </span>{job.reasoning || 'This role is relevant to your search and experience.'}</p></div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-800 pt-4"><button onClick={() => setExpanded(value => !value)} className="flex items-center gap-1.5 text-sm font-medium text-slate-400 transition hover:text-white">Match details <ChevronDown className={`h-4 w-4 transition ${expanded ? 'rotate-180' : ''}`} /></button><div className="flex gap-2"><button onClick={onSave} aria-label={saved ? 'Remove saved job' : 'Save job'} className={`rounded-lg border p-2.5 transition ${saved ? 'border-cyan-300/40 bg-cyan-300/10 text-cyan-200' : 'border-slate-700 text-slate-300 hover:bg-slate-800'}`}><Bookmark className={`h-4 w-4 ${saved ? 'fill-current' : ''}`} /></button><a href={job.apply_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-200">View & apply <ExternalLink className="h-4 w-4" /></a></div></div>
    <AnimatePresence>{expanded && <Motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="mt-5 grid gap-5 border-t border-slate-800 pt-5 sm:grid-cols-2"><div><p className="mb-2 text-sm font-semibold text-emerald-300">Matched skills</p><div className="flex flex-wrap gap-2">{(job.matched_skills || []).length ? job.matched_skills.map(skill => <span key={skill} className="rounded-md bg-emerald-400/10 px-2 py-1 text-xs text-emerald-200">{skill}</span>) : <span className="text-sm text-slate-500">Based on your overall profile</span>}</div></div><div><p className="mb-2 text-sm font-semibold text-amber-300">Worth reviewing</p><div className="flex flex-wrap gap-2">{(job.missing_skills || []).map(skill => <span key={skill} className="rounded-md bg-amber-400/10 px-2 py-1 text-xs text-amber-200">{skill}</span>)}</div></div></div></Motion.div>}</AnimatePresence>
  </div></Motion.article>;
}
