import React, { useState } from 'react';
import { useDropzone } from 'react-dropzone';
import { FileText, MapPin, Search, Upload, X } from 'lucide-react';

const suggestions = ['Software Engineer', 'Data Analyst', 'Frontend Developer', 'Product Manager'];

export default function SearchBar({ onSearch, isLoading }) {
  const [query, setQuery] = useState(''); const [location, setLocation] = useState(''); const [file, setFile] = useState(null);
  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop: files => setFile(files[0] || null), accept: { 'application/pdf': ['.pdf'] }, maxFiles: 1 });
  const submit = event => { event?.preventDefault(); if (query.trim() || file) onSearch({ query: query.trim(), location: location.trim(), file }); };
  return <form onSubmit={submit} className="mx-auto max-w-4xl rounded-2xl border border-slate-700/70 bg-slate-900/80 p-4 shadow-2xl shadow-black/30 backdrop-blur sm:p-5">
    <div className="grid gap-3 md:grid-cols-[1.5fr_1fr_auto]"><label className="relative block"><span className="sr-only">Role or keyword</span><Search className="pointer-events-none absolute left-3 top-3.5 h-5 w-5 text-slate-500"/><input value={query} onChange={e => setQuery(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-[#0c1220] py-3 pl-10 pr-3 text-sm text-white outline-none transition focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/15" placeholder="Role, skill, or company" /></label><label className="relative block"><span className="sr-only">Location</span><MapPin className="pointer-events-none absolute left-3 top-3.5 h-5 w-5 text-slate-500"/><input value={location} onChange={e => setLocation(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-[#0c1220] py-3 pl-10 pr-3 text-sm text-white outline-none transition focus:border-cyan-400 focus:ring-2 focus:ring-cyan-400/15" placeholder="Location or Remote" /></label><button disabled={isLoading || (!query.trim() && !file)} className="flex items-center justify-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-200 disabled:cursor-not-allowed disabled:opacity-45">{isLoading ? <><span className="h-4 w-4 animate-spin rounded-full border-2 border-slate-950/25 border-t-slate-950"/>Searching</> : <><Search className="h-4 w-4"/>Search jobs</>}</button></div>
    <div className="mt-3 flex flex-wrap gap-2">{suggestions.map(item => <button type="button" key={item} onClick={() => setQuery(item)} className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-400 transition hover:border-cyan-400/50 hover:text-cyan-200">{item}</button>)}</div>
    <div {...getRootProps()} className={`mt-4 flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-dashed p-3 transition ${isDragActive ? 'border-cyan-300 bg-cyan-300/10' : 'border-slate-700 bg-slate-950/30 hover:border-slate-500'}`}><input {...getInputProps()} />{file ? <><div className="flex min-w-0 items-center gap-3"><FileText className="h-5 w-5 shrink-0 text-cyan-300"/><span className="truncate text-sm text-slate-200">{file.name}</span><span className="hidden text-xs text-emerald-300 sm:inline">Ready to analyze</span></div><button type="button" onClick={event => { event.stopPropagation(); setFile(null); }} className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-white"><X className="h-4 w-4"/></button></> : <><div className="flex items-center gap-3 text-sm text-slate-400"><Upload className="h-5 w-5 text-cyan-300"/><span><b className="font-medium text-slate-200">Upload a resume</b> to personalize matches</span></div><span className="text-xs text-slate-500">PDF only</span></>}</div>
  </form>;
}
